on:
  push:
    branches:
      - "main"
  pull_request:

name: "CI"

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  ci:
    uses: "WebProject-xyz/.github/.github/workflows/ci.yml@main"
    secrets: inherit
